### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by vivekkj123** [vivekkj123/tekwiza-web#1]
- [x] Create Contact Us page
- [x] Create pages for events which doesn't have their own websites (We can use a single page code for all events and workshops)
- [x] Create Paper/Project Presentation page (Content: https://techfest.sahrdaya.ac.in/index.php/paper_poster/ )
- [x] Make all mobile responsive
- [x] Move Poster/Paper presentation to events page under Other Events
- [x] Create Workshops page (We can make attractive by using slider code? )
- [x] Add Rainbow gradient on hover for cards in event, workshop pages (like https://githubuniverse.com/events/detail/virtual-schedule)
- [ ] Add Prize money in a attractive way (Not in tabular)
- [ ] Create Our Team Page
- [x] Create sponsors section in home page (No need to categorize, but sponsors with more sponsored on top)
- [ ] Make more interactive and dynamic by adding more animations and hover effects
- [ ] instead of plain black, we can consider dark backgrounds or gradients
- [ ] suggestion: A Map/Aerial shot in which locations of every event is marked.

** -- Updated On 11 Nov 2022 --**
